# File: .github/workflows/repo-sync.yml
name: 同步上游代码
on:
  schedule:
    - cron: '1 0,4,8,12,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-lxk0301-repo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Sync jd_scripts -> main
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          #source_repo: "https://github.com/LXK9301/jd_scripts.git"
          source_repo: "https://gitee.com/lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}

      #- name: Merge main -> master
      #  uses: devmasx/merge-branch@v1.3.1
      #  with:
      #    type: now
      #    from_branch: main
      #    target_branch: master
      #    github_token: ${{ github.PAT }}
